import {placeTypes,symbolType,symbolUrl} from './placeSymbols';
import {MapCompass} from './MapCompass';
import {MeasureTool} from './MeasureTool';
import {forwardRef,useEffect,useImperativeHandle,useRef,useState} from 'react';
import Map from 'ol/Map';import View from 'ol/View';import Feature from 'ol/Feature';import GeoJSON from 'ol/format/GeoJSON';import WMTSCapabilities from 'ol/format/WMTSCapabilities';
import WKT from 'ol/format/WKT';
import {transformExtent} from 'ol/proj';
import {X} from 'lucide-react';
import type {OfficialPlace} from './officialSearch';
import type WMTS from 'ol/source/WMTS';import VectorSource from 'ol/source/Vector';import VectorLayer from 'ol/layer/Vector';import TileLayer from 'ol/layer/Tile';
import {createBasemapSource} from './basemaps';
import {mapColor,colorOutline,mapWidth} from './mapColors';
import {Fill,Stroke,Style,Circle as CircleStyle,Text,Icon} from 'ol/style';import {Draw,Modify} from 'ol/interaction';import {defaults as defaultControls} from 'ol/control';import {fromLonLat,transform} from 'ol/proj';import {register} from 'ol/proj/proj4';import proj4 from 'proj4';import Point from 'ol/geom/Point';import Circle from 'ol/geom/Circle';import {getPointResolution} from 'ol/proj';
import type {Entry,Geometry,Kind} from './types';import {label} from './types';import 'ol/ol.css';
proj4.defs('EPSG:3301','+proj=lcc +lat_0=57.51755393055556 +lon_0=24 +lat_1=59.33333333333334 +lat_2=58 +x_0=500000 +y_0=6375000 +ellps=GRS80 +units=m +no_defs');register(proj4);
const format=new GeoJSON();
const pointIcons=Object.fromEntries(placeTypes.map(t=>[t,new Icon({src:symbolUrl(t),width:32,height:32})]));
export type MapHandle={fit:()=>void;focus:(e:Entry)=>void;undo:()=>void;finish:()=>void;locate:(coords:number[],accuracy:number)=>void;boundaryCheck:(coords:number[],accuracy?:number)=>string;geometry:()=>Geometry|null};
type Props={measuring:boolean;onCloseMeasure:()=>void;searchResult:OfficialPlace|null;onClearSearch:()=>void;entries:Entry[];base:string;boundaryVisible:boolean;drawing:Kind|null;drawingColor:string;drawingWidth:number;drawType:'Point'|'LineString'|'Polygon';editGeometry:Geometry|null;onGeometry:(g:Geometry)=>void;onSelect:(id:string)=>void;onReady:()=>void;onError:(s:string)=>void};
export const MapCanvas=forwardRef<MapHandle,Props>(function MapCanvas(p,ref){const el=useRef<HTMLDivElement>(null),map=useRef<Map|null>(null),official=useRef(new VectorSource()),source=useRef(new VectorSource()),draft=useRef(new VectorSource()),gps=useRef(new VectorSource()),search=useRef(new VectorSource()),draw=useRef<Draw|null>(null),tiles=useRef<Record<string,TileLayer<WMTS>>>({});const callbacks=useRef(p);callbacks.current=p;const [tileProblem,setTileProblem]=useState('');const [mapInstance,setMapInstance]=useState<Map|null>(null);
useImperativeHandle(ref,()=>({fit(){if(map.current&&!official.current.isEmpty())map.current.getView().fit(official.current.getExtent()!,{padding:[85,45,115,45],duration:500});},focus(e){const f=format.readFeature({type:'Feature',geometry:e.geometry},{dataProjection:'EPSG:4326',featureProjection:'EPSG:3857'}) as Feature;map.current?.getView().fit(f.getGeometry()!.getExtent(),{padding:[130,80,170,80],maxZoom:17,duration:450});},undo(){draw.current?.removeLastPoint();},finish(){draw.current?.finishDrawing();},geometry(){const f=draft.current.getFeatures()[0];return f?format.writeGeometryObject(f.getGeometry()!,{dataProjection:'EPSG:4326',featureProjection:'EPSG:3857'}) as Geometry:null;},locate(c,a){const pt=fromLonLat(c);gps.current.clear();gps.current.addFeatures([new Feature(new Circle(pt,a/getPointResolution('EPSG:3857',1,pt))),new Feature(new Point(pt))]);map.current?.getView().animate({center:pt,zoom:16,duration:500});},boundaryCheck(c,a=0){const f=official.current.getFeatures()[0];if(!f)return 'Piir laadimata';const g=f.getGeometry()!.clone().transform('EPSG:3857','EPSG:3301') as any;const pt=transform(c,'EPSG:4326','EPSG:3301');const inside=g.intersectsCoordinate(pt);const ring=g.getLinearRing?.(0)||g;const near=ring.getClosestPoint(pt);if(Math.hypot(near[0]-pt[0],near[1]-pt[1])<=a)return 'Piiri lähedal · GPS ebatäpne';return inside?'Jahiala sees':'Väljaspool jahiala';}}),[]);
useEffect(()=>{let disposed=false;const boundaryLayer=new VectorLayer({source:official.current,style:[new Style({stroke:new Stroke({color:'#fff',width:6}),fill:new Fill({color:'rgba(27,76,57,.035)'})}),new Style({stroke:new Stroke({color:'#d97726',width:3})})]});
const entriesLayer=new VectorLayer({source:source.current,declutter:true,style:(f,res)=>{
 const kind=f.get('kind') as Kind,color=mapColor(kind,f.get('color')),named=kind==='area'||kind==='line';
 const width=mapWidth(kind,f.get('stroke_width')),house=kind==='place';
 const mainStyle=new Style({stroke:new Stroke({color,width,lineDash:kind==='sign'?[6,4]:undefined}),fill:new Fill({color:kind==='area'?color+'20':'rgba(124,72,148,.08)'}),image:house?pointIcons[symbolType(f.get('objectType'))]:new CircleStyle({radius:kind==='observation'?8:7,fill:new Fill({color}),stroke:new Stroke({color:'#fff',width:2})}),text:res<18?new Text({text:(kind==='sign'?'↟ ':kind==='observation'?'◉ ':'')+f.get('label'),offsetY:house?-26:-18,font:'600 14px system-ui',fill:new Fill({color:'#162f28'}),stroke:new Stroke({color:'#fff',width:4})}):undefined});
 return named?[new Style({stroke:new Stroke({color:colorOutline(color),width:width+3})}),mainStyle]:mainStyle;
}});
const draftStyle=()=>{const color=callbacks.current.drawingColor,width=callbacks.current.drawingWidth;return [
 new Style({stroke:new Stroke({color:colorOutline(color),width:width+3})}),
 new Style({stroke:new Stroke({color,width}),fill:new Fill({color:color+'20'}),image:new CircleStyle({radius:7,fill:new Fill({color}),stroke:new Stroke({color:colorOutline(color),width:2})})})
];};
const draftLayer=new VectorLayer({source:draft.current,style:draftStyle});
const gpsLayer = new VectorLayer({source:gps.current,style:new Style({fill:new Fill({color:'rgba(38,126,231,.13)'}),stroke:new Stroke({color:'#2680eb',width:1}),image:new CircleStyle({radius:7,fill:new Fill({color:'#1976df'}),stroke:new Stroke({color:'#fff',width:3})})})});
const searchLayer=new VectorLayer({source:search.current,style:[new Style({stroke:new Stroke({color:'#fff',width:8})}),new Style({stroke:new Stroke({color:'#d72f79',width:4}),fill:new Fill({color:'rgba(215,47,121,.10)'}),image:new CircleStyle({radius:10,fill:new Fill({color:'#d72f79'}),stroke:new Stroke({color:'#fff',width:3})})})]});
const m=new Map({target:el.current!,view:new View({center:fromLonLat([24.887,58.638]),zoom:11}),controls:defaultControls({zoom:false,rotate:false,attribution:false}),layers:[boundaryLayer,entriesLayer,draftLayer,gpsLayer,searchLayer]});map.current=m;setMapInstance(m);
m.on('singleclick',ev=>{if(callbacks.current.drawing||callbacks.current.measuring)return;m.forEachFeatureAtPixel(ev.pixel,f=>{const id=f.get('entryId');if(id){callbacks.current.onSelect(id);return true;}},{hitTolerance:12,layerFilter:l=>l===entriesLayer});});
fetch(import.meta.env.BASE_URL+'data/boundary.geojson').then(r=>{if(!r.ok)throw Error();return r.json();}).then(j=>{if(disposed)return;official.current.addFeatures(format.readFeatures(j,{dataProjection:'EPSG:4326',featureProjection:'EPSG:3857'}));if(!callbacks.current.searchResult&&!callbacks.current.measuring)m.getView().fit(official.current.getExtent()!,{padding:[90,50,110,50]});callbacks.current.onReady();}).catch(()=>callbacks.current.onError('Ametliku piiri laadimine ebaõnnestus.'));
fetch(import.meta.env.BASE_URL+'data/wmts.xml').then(r=>{if(!r.ok)throw Error();return r.text();}).then(xml=>{if(disposed)return;const cap=new WMTSCapabilities().read(xml);for(const name of ['kaart','foto','hybriid']){const s=createBasemapSource(cap,name);s.on('tileloaderror',()=>{if(!disposed&&tiles.current[name]?.getVisible())setTileProblem('Aluskaart ei lae. Kontrolli ühendust või vali teine aluskaart.');});s.on('tileloadend',()=>{if(!disposed&&tiles.current[name]?.getVisible())setTileProblem('');});const layer=new TileLayer({source:s,visible:name==='kaart'});tiles.current[name]=layer;m.getLayers().insertAt(['kaart','foto','hybriid'].indexOf(name),layer);}setBase(callbacks.current.base);}).catch(()=>{if(!disposed)setTileProblem('Aluskaardi kirjeldus ei avanenud. Laadi leht uuesti.');});
function setBase(b:string){for(const [name,l]of Object.entries(tiles.current))l.setVisible(name==='kaart'?b==='kaart':name==='foto'?b!=='kaart':b==='hybriid');}
return()=>{disposed=true;m.setTarget(undefined);map.current=null;official.current.clear();};},[]);
useEffect(()=>{
 search.current.clear();const place=p.searchResult,m=map.current;if(!place||!m)return;
 let shape:import('ol/geom/Geometry').default=new Point(fromLonLat(place.coordinates));
 try{
  const raw=place.geometry;
  const parsed=raw?.format==='wkt'?new WKT().readGeometry(raw.value,{dataProjection:'EPSG:3301',featureProjection:'EPSG:3857'}):raw?.format==='geojson'?format.readGeometry(raw.value,{dataProjection:'EPSG:4326',featureProjection:'EPSG:3857'}):null;
  if(parsed&&parsed.getExtent().every(Number.isFinite))shape=parsed;
 }catch{/* The service's valid reference point remains usable if a shape is unavailable. */}
 search.current.addFeature(new Feature(shape));
 const target=shape.getType()==='Point'&&place.extent?transformExtent(place.extent,'EPSG:4326','EPSG:3857'):shape.getExtent();
 const size=m.getSize()||[window.innerWidth,window.innerHeight],desktop=size[0]>=1000;
 const padding=desktop?[180,80,175,380]:[205,35,180,35];
 const scale=Math.min(1,Math.max(size[1]-100,0)/(padding[0]+padding[2]));
 padding[0]*=scale;padding[2]*=scale;
 m.getView().fit(target,{padding,maxZoom:16,duration:450});
},[p.searchResult]);
useEffect(()=>{source.current.clear();source.current.addFeatures(p.entries.map(e=>{const f=format.readFeature({type:'Feature',geometry:e.geometry,properties:{kind:e.kind,objectType:e.properties.type,label:label(e),entryId:e.id,color:mapColor(e.kind,e.properties.color),stroke_width:mapWidth(e.kind,e.properties.stroke_width)}},{dataProjection:'EPSG:4326',featureProjection:'EPSG:3857'}) as Feature;return f;}));},[p.entries]);
useEffect(()=>{for(const [name,l]of Object.entries(tiles.current))l.setVisible(name==='kaart'?p.base==='kaart':name==='foto'?p.base!=='kaart':p.base==='hybriid');},[p.base]);
useEffect(()=>{map.current?.getLayers().getArray().find(l=>l instanceof VectorLayer&&l.getSource()===official.current)?.setVisible(p.boundaryVisible);},[p.boundaryVisible]);
useEffect(()=>{draft.current.changed();draw.current?.getOverlay().changed();},[p.drawingColor,p.drawingWidth]);
useEffect(()=>{const m=map.current;if(!m)return;draft.current.clear();if(!p.drawing)return;let modify:Modify|null=null;if(p.editGeometry){draft.current.addFeature(format.readFeature({type:'Feature',geometry:p.editGeometry},{dataProjection:'EPSG:4326',featureProjection:'EPSG:3857'}) as Feature);modify=new Modify({source:draft.current});m.addInteraction(modify);modify.on('modifyend',()=>{const f=draft.current.getFeatures()[0];callbacks.current.onGeometry(format.writeGeometryObject(f.getGeometry()!,{dataProjection:'EPSG:4326',featureProjection:'EPSG:3857'}) as Geometry);});}else{const d=new Draw({source:draft.current,type:p.drawType,style:()=>{const color=callbacks.current.drawingColor,width=callbacks.current.drawingWidth;return [new Style({stroke:new Stroke({color:colorOutline(color),width:width+3})}),new Style({stroke:new Stroke({color,width}),fill:new Fill({color:color+'20'}),image:new CircleStyle({radius:7,fill:new Fill({color}),stroke:new Stroke({color:colorOutline(color),width:2})})})];}});draw.current=d;m.addInteraction(d);d.on('drawstart',()=>draft.current.clear());d.on('drawend',ev=>callbacks.current.onGeometry(format.writeGeometryObject(ev.feature.getGeometry()!,{dataProjection:'EPSG:4326',featureProjection:'EPSG:3857'}) as Geometry));}return()=>{if(draw.current)m.removeInteraction(draw.current);if(modify)m.removeInteraction(modify);draw.current=null;draft.current.clear();};},[p.drawing,p.drawType,p.editGeometry]);
return <>{mapInstance&&<MapCompass map={mapInstance}/>} {p.measuring&&mapInstance&&<MeasureTool map={mapInstance} onClose={p.onCloseMeasure}/>}<div ref={el} className="map" aria-label="Pärnjõe jahipiirkonna interaktiivne kaart"/>{p.searchResult&&<div className="search-selection"><div><strong>{p.searchResult.name}</strong><small>{p.searchResult.type} · {p.searchResult.source}</small></div><button className="iconbtn" aria-label="Peida otsingutulemus" onClick={p.onClearSearch}><X size={20}/></button></div>}{tileProblem&&<div className="basemap-error" role="alert">{tileProblem}</div>}</>;});
